stages:
  - test
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test-frontend:
  image: nikolaik/python-nodejs:python3.8-nodejs12
  stage: test
  when: always
  cache: {}
  before_script:
    - cd client
  script:
    - npm ci
    - npm run lint -- --max-warnings 0

test-backend:
  image: nikolaik/python-nodejs:python3.8-nodejs12
  stage: test
  script:
    - ./build.py bootstrap --python-only
    - ./build.py test

build:
  image: nikolaik/python-nodejs:python3.8-nodejs12
  stage: build
  when: always
  script:
    - ./build.py build
  artifacts:
    paths:
      - dist/
