version: "3.5"

services:
  hub:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      HTTP_HOST: 0.0.0.0
    ports:
      - 3000:3000
  db:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    environment:
      POSTGRES_PASSWORD: password
